/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project2;

import p1.api.*;

public class App {
    public String getGreeting() {
        return new Foo().getBar() + new Foo().getFubar() ;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
